// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node ./prisma/seed.js",
  },
  datasource: {
    // Use direct connection for migrations (faster, no pooler timeout)
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  } as any,
});
